FROM node:22-alpine

RUN apk add --no-cache git

WORKDIR /app

RUN git clone --depth 1 --branch 2026-03-29 https://github.com/Kethen/aemu_postoffice.git .

WORKDIR /app/server_njs

RUN npm install
RUN npm run build

ENV AEMU_POSTOFFICE_CONFIG_PATH=/app/server_njs/config.json

EXPOSE 27313/tcp

CMD ["npm", "start"]
